# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
pr:
- master
- dev

pool: 'Default'

steps:
# Install AutoRest package.
- task: Npm@1
  inputs:
    command: 'custom'
    customCommand: 'install -g @autorest/autorest@3.0.6114'

# Generate modules.
- task: PowerShell@2
  inputs:
    filePath: '$(System.DefaultWorkingDirectory)/tools/GenerateModules.ps1'
    arguments: '-RepositoryName $(Repository_Name) -RepositoryApiKey $(Api_Key) -ModuleVersion $(Module_Version) -ArtifactsLocation $(Build.ArtifactStagingDirectory) -UseLocalDoc -BetaGraphVersion'
    pwsh: true

- script: |
    echo Build complete.
  displayName: 'Complete'